<?php

namespace MicroShard\JsonRpcServer;

class ErrorCode
{
    const MALFORMED_REQUEST_JSON = 100;
    const MISSING_RESOURCE = 101;
    const MISSING_METHOD = 102;

    const INVALID_AUTHORIZATION = 120;

    const INVALID_API_PATH = 200;
    const INVALID_CONSTRUCTOR_HANDLER = 201;
    const FAULTY_CONSTRUCTOR_HANDLER = 202;
    const INVALID_EXTENSION_HANDLER = 203;
    const FAULTY_EXTENSION_HANDLER = 204;

    const ERROR_CODE_UNKNOWN = 999;
}